### PR TITLE
feat: nrql editor component

### PR DESCRIPTION
**Pull request by amit-y**

### CODE REVIEW

**Review by shahramk — COMMENTED** [review]
it seems the style file is not working for me. the style is messed up. other than than functionally it works as expected.

**Comment by aso1124** [comment]
These keywords and functions aren't included in patterns.js:

Keywords:
IN|ORDER BY|LIMIT|OFFSET|WITH|SLIDE BY|WITH METRIC_FORMAT

WITH can be used in WITH ... AS clauses, as well as those other clauses that start with WITH

Functions:
aggregationendtime|bucketPercentile|cardinality|dateOf|derivative|dimensions|include|exclude|latestrate|minuteOf|mod|montnOf|quarterOf|predictLinear|round|stdvar|weekOf|yearOf|accountId|aparse|concat|earliest|eventType|getField|if|length|lower|position|string|substring|upper|abs|clamp_max|clamp_min|exp|pow|sqrt

include/exclude are part of the dimensions function

**Comment by amit-y** [comment]
NRQL styles were fixed in commit cc40e12

**Comment by amit-y** [comment]
Updated `patterns.js` with newer functions and keywords listed in @aso1124's [comment](#issuecomment-1508601819)

**Comment by amit-y** [comment]
⚠️  **IMPORTANT** Please do not merge until #56 has been merged in!

**Review by aso1124 — APPROVED** [review]
👍

**Pull request merged**
